import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { TriangleAlert } from "lucide-react";
import { ProposalEditor } from "@/components/editor/proposal-editor";
import { SystemStatusToasts } from "@/components/system-status-toasts";
import { getSystemStatus } from "@/server/system/status";
import { prisma } from "@/server/db";
import { generationSource } from "@/server/proposal/generate";
import { proposalUrlFor } from "@/server/tracking/record";
import { proposalContentSchema } from "@/types/proposal";

/** Always reflects the latest saved content. */
export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Edit proposal",
  // `robots` comes from the root layout; declaring it here would replace it.
};

export default async function EditorPage(props: {
  // Next 16: params and searchParams are Promises and must be awaited.
  params: Promise<{ id: string }>;
  searchParams: Promise<{ engine?: string; fallback?: string }>;
}) {
  const { id } = await props.params;
  const { engine, fallback } = await props.searchParams;

  // A database outage shouldn't show the rep a stack trace. Missing proposal is
  // a genuine 404; an unreachable database is a different problem and gets a
  // different message.
  let proposal;
  try {
    proposal = await prisma.proposal.findUnique({ where: { id } });
  } catch (error) {
    return (
      <div className="mx-auto w-full max-w-2xl px-6 py-16">
        <div className="flex gap-3 rounded-lg border bg-muted/40 p-5 text-sm">
          <TriangleAlert
            className="mt-0.5 size-4 shrink-0 text-muted-foreground"
            aria-hidden
          />
          <div>
            <p className="font-medium text-foreground">
              Can&apos;t reach the database
            </p>
            <p className="mt-1 text-muted-foreground">
              Start it with{" "}
              <code className="rounded bg-muted px-1 py-0.5 text-xs">
                npm run db:dev
              </code>
              , then reload. If it was already running, restart the dev server so
              it picks up a changed DATABASE_URL.
            </p>
            <p className="mt-2 text-xs text-muted-foreground">
              {error instanceof Error ? error.message : String(error)}
            </p>
          </div>
        </div>
      </div>
    );
  }

  if (!proposal) notFound();

  // Parse rather than cast. A proposal written by an older schema version would
  // otherwise crash the editor with a stack trace; this reports it instead.
  const parsed = proposalContentSchema.safeParse(proposal.proposalJson);
  if (!parsed.success) {
    const issue = parsed.error.issues[0];
    return (
      <div className="mx-auto w-full max-w-2xl px-6 py-16">
        <div className="flex gap-3 rounded-lg border border-destructive/30 bg-destructive/8 p-5 text-sm">
          <TriangleAlert
            className="mt-0.5 size-4 shrink-0 text-destructive"
            aria-hidden
          />
          <div>
            <p className="font-medium text-foreground">
              This proposal&apos;s stored content doesn&apos;t match the current
              schema
            </p>
            <p className="mt-1 text-muted-foreground">
              {issue?.path.join(".")}: {issue?.message}
            </p>
            <p className="mt-2 text-muted-foreground">
              It was probably written before a schema change. Regenerate it from
              the transcript, or fix the row directly.
            </p>
          </div>
        </div>
      </div>
    );
  }

  // Database, because every save and publish writes. Generation is reported
  // per-proposal below instead — what matters here is which engine produced
  // THIS proposal, not what the current setting happens to be.
  const status = await getSystemStatus(["database"]);

  // Announce what actually generated this proposal. Matters most when Claude
  // was configured but fell back — otherwise that downgrade is invisible.
  const issues = [...status.issues];
  if (engine === "claude") {
    issues.push({
      id: `gen-${id}`,
      level: "info",
      title: "Generated by Claude",
      detail: "claude-opus-5",
    });
  } else if (engine === "offline") {
    issues.push({
      id: `gen-${id}`,
      level: "warning",
      title: fallback ? "Claude unavailable" : "Generated offline",
      detail: fallback ? `${fallback} — used offline` : "keyword matching",
      debug:
        "These sections were produced by keyword matching, not written by " +
        "Claude. Review the wording before publishing.",
    });
  }

  return (
    <>
      <SystemStatusToasts issues={issues} />
      <ProposalEditor
        proposalId={proposal.id}
        slug={proposal.slug}
        status={proposal.status}
        version={proposal.version}
        publicUrl={proposalUrlFor(proposal.slug)}
        initialContent={parsed.data}
        repName={proposal.repName}
        practiceName={proposal.practiceName}
        contactName={proposal.contactName}
        offlineMode={generationSource() === "offline"}
      />
    </>
  );
}
